/*
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/
 */

use anyhow::Result;
use proc_macro2::{Span, TokenStream};
use quote::{format_ident, quote};
use serde::{Deserialize, Serialize};
use ubrn_common::CrateMetadata;
use uniffi_bindgen::{
    interface::{FfiArgument, FfiFunction, FfiType},
    ComponentInterface,
};

use crate::{
    bindings::{extensions::ComponentInterfaceExt as _, metadata::ModuleMetadata},
    switches::SwitchArgs,
};

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub(crate) struct Config {}

pub(crate) fn generate_rs(
    ci: &ComponentInterface,
    _module: &ModuleMetadata,
    _config: &Config,
    _switches: &SwitchArgs,
    try_format_code: bool,
) -> Result<String> {
    if ci.has_callbacks() || ci.has_async_calls() {
        anyhow::bail!(
            "The napi flavor currently supports synchronous UniFFI APIs only. \
             Callback interfaces and async methods are not yet supported."
        );
    }

    let externs: Result<Vec<_>> = ci
        .iter_ffi_functions_js_to_abi_rust()
        .map(|func| ffi_function_decl_c_abi(&func))
        .collect();

    let wrappers: Result<Vec<_>> = ci
        .iter_ffi_functions_js_to_abi_rust()
        .map(|func| ffi_function_wrapper(&func))
        .collect();

    let externs = externs?;
    let wrappers = wrappers?;

    let src = quote! {
        // Generated by uniffi-bindgen-react-native
        use napi::bindgen_prelude::{BigInt, Buffer};
        use napi_derive::napi;

        pub mod uniffi {
            #[allow(unused_imports)]
            pub use uniffi_core::{RustBuffer, RustCallStatus, RustCallStatusCode};
            pub type VoidPointer = *const std::ffi::c_void;
        }

        #[napi]
        pub struct RustCallStatus {
            code_value: i8,
            error_buf: Option<Buffer>,
        }

        #[napi]
        impl RustCallStatus {
            #[napi(constructor)]
            pub fn new() -> Self {
                Self {
                    code_value: 0,
                    error_buf: None,
                }
            }

            #[napi(getter)]
            pub fn code(&self) -> i8 {
                self.code_value
            }

            #[napi(setter)]
            pub fn set_code(&mut self, value: i8) {
                self.code_value = value;
            }

            #[napi(getter, js_name = "errorBuf")]
            pub fn error_buf(&self) -> Option<Buffer> {
                self.error_buf.clone()
            }

            #[napi(setter, js_name = "errorBuf")]
            pub fn set_error_buf(&mut self, bytes: Option<Buffer>) {
                self.error_buf = bytes;
            }
        }

        impl Default for RustCallStatus {
            fn default() -> Self {
                Self::new()
            }
        }

        impl RustCallStatus {
            fn copy_from(&mut self, rust: uniffi::RustCallStatus) {
                self.code_value = rust.code as i8;
                let buf = std::mem::ManuallyDrop::into_inner(rust.error_buf).destroy_into_vec();
                self.error_buf = Some(Buffer::from(buf));
            }
        }

        extern "C" {
            #(#externs)*
        }

        #(#wrappers)*
    };

    formatted(src, try_format_code)
}

pub(crate) fn generate_entrypoint(
    crate_: &CrateMetadata,
    modules: &[ModuleMetadata],
) -> Result<String> {
    let crate_ident = format_ident!("{}", crate_.library_name());
    let mods: Vec<_> = modules
        .iter()
        .map(|m| {
            let namespace = format_ident!("{}", m.rs_module());
            quote! { mod #namespace; }
        })
        .collect();

    let src = quote! {
        #[allow(unused_imports)]
        use #crate_ident;

        #(#mods)*
    };

    formatted(src, true)
}

fn formatted(tokens: TokenStream, try_format_code: bool) -> Result<String> {
    let code = if try_format_code {
        let syntax_tree = syn::parse2(tokens)?;
        prettyplease::unparse(&syntax_tree)
    } else {
        TokenStream::to_string(&tokens)
    };
    Ok(code)
}

fn ffi_function_decl_c_abi(func: &FfiFunction) -> Result<TokenStream> {
    let func_ident = format_ident!("{}", func.name());
    let mut args = Vec::new();
    for arg in func.arguments() {
        args.push(arg_decl(arg, ffi_type_rust)?);
    }
    if func.has_rust_call_status_arg() {
        args.push(quote! { status_: &mut uniffi::RustCallStatus, });
    }
    let return_suffix = match func.return_type() {
        Some(return_type) => {
            let ty = ffi_type_rust(return_type)?;
            quote! { -> #ty }
        }
        None => quote! {},
    };

    Ok(quote! {
        fn #func_ident(#(#args)*) #return_suffix;
    })
}

fn ffi_function_wrapper(func: &FfiFunction) -> Result<TokenStream> {
    let ffi_ident = format_ident!("{}", func.name());
    let js_ident = format_ident!("ubrn_{}", func.name());
    let js_name = syn::LitStr::new(&js_ident.to_string(), Span::call_site());

    let args = func.arguments();
    let mut js_args = Vec::new();
    let mut args_into_rust = Vec::new();
    for arg in &args {
        let ident = format_ident!("{}", arg.name());
        js_args.push(arg_decl(arg, ffi_type_js)?);
        args_into_rust.push(convert_to_rust(&ident, &arg.type_())?);
    }

    let has_return = func.return_type().is_some();
    let return_suffix = if let Some(type_) = func.return_type() {
        let ty = ffi_type_js(type_)?;
        quote! { -> #ty }
    } else {
        quote! {}
    };

    if func.has_rust_call_status_arg() {
        js_args.push(quote! { f_status_: &mut RustCallStatus, });
        if has_return {
            let return_type = func
                .return_type()
                .expect("checked above: return type exists");
            let return_expr = convert_to_js(quote! { value_ }, return_type)?;
            Ok(quote! {
                #[napi(js_name = #js_name)]
                pub fn #js_ident(#(#js_args)*) #return_suffix {
                    let mut u_status_ = uniffi::RustCallStatus::default();
                    let value_ = unsafe { #ffi_ident(#(#args_into_rust)* &mut u_status_) };
                    f_status_.copy_from(u_status_);
                    #return_expr
                }
            })
        } else {
            Ok(quote! {
                #[napi(js_name = #js_name)]
                pub fn #js_ident(#(#js_args)*) {
                    let mut u_status_ = uniffi::RustCallStatus::default();
                    unsafe { #ffi_ident(#(#args_into_rust)* &mut u_status_) };
                    f_status_.copy_from(u_status_);
                }
            })
        }
    } else if has_return {
        let return_type = func
            .return_type()
            .expect("checked above: return type exists");
        let return_expr = convert_to_js(quote! { value_ }, return_type)?;
        Ok(quote! {
            #[napi(js_name = #js_name)]
            pub fn #js_ident(#(#js_args)*) #return_suffix {
                let value_ = unsafe { #ffi_ident(#(#args_into_rust)*) };
                #return_expr
            }
        })
    } else {
        Ok(quote! {
            #[napi(js_name = #js_name)]
            pub fn #js_ident(#(#js_args)*) {
                unsafe { #ffi_ident(#(#args_into_rust)*) };
            }
        })
    }
}

fn arg_decl(
    arg: &FfiArgument,
    to_type: fn(&FfiType) -> Result<TokenStream>,
) -> Result<TokenStream> {
    let ident = format_ident!("{}", arg.name());
    let ty = to_type(&arg.type_())?;
    Ok(quote! { #ident: #ty, })
}

fn convert_to_rust(ident: &proc_macro2::Ident, type_: &FfiType) -> Result<TokenStream> {
    Ok(match type_ {
        FfiType::UInt64 | FfiType::Handle => quote! {{
            let (is_negative, value, _lossless) = #ident.get_u64();
            if is_negative {
                panic!("Expected non-negative bigint value");
            }
            value
        }, },
        FfiType::Int64 => quote! {{
            let (value, _lossless) = #ident.get_i64();
            value
        }, },
        FfiType::RustBuffer(_) | FfiType::ForeignBytes => {
            quote! { uniffi::RustBuffer::from_vec(#ident.to_vec()), }
        }
        FfiType::VoidPointer => quote! {{
            let (is_negative, value, _lossless) = #ident.get_u64();
            if is_negative {
                panic!("Expected non-negative pointer bigint value");
            }
            value as uniffi::VoidPointer
        }, },
        FfiType::Reference(_) | FfiType::MutReference(_) => {
            anyhow::bail!("The napi flavor does not support reference FFI argument types yet")
        }
        FfiType::Callback(_) | FfiType::Struct(_) => {
            anyhow::bail!("The napi flavor does not support callback/vtable FFI types yet")
        }
        _ => quote! { #ident, },
    })
}

fn convert_to_js(value: TokenStream, type_: &FfiType) -> Result<TokenStream> {
    Ok(match type_ {
        FfiType::UInt64 | FfiType::Handle => quote! { BigInt::from(#value) },
        FfiType::Int64 => quote! { BigInt::from(#value) },
        FfiType::RustBuffer(_) | FfiType::ForeignBytes => {
            quote! { Buffer::from(#value.destroy_into_vec()) }
        }
        FfiType::VoidPointer => quote! { BigInt::from(#value as u64) },
        FfiType::Reference(_) | FfiType::MutReference(_) => {
            anyhow::bail!("The napi flavor does not support reference FFI return types yet")
        }
        FfiType::Callback(_) | FfiType::Struct(_) => {
            anyhow::bail!("The napi flavor does not support callback/vtable FFI types yet")
        }
        _ => value,
    })
}

fn ffi_type_js(type_: &FfiType) -> Result<TokenStream> {
    Ok(match type_ {
        FfiType::UInt8 => quote! { u8 },
        FfiType::Int8 => quote! { i8 },
        FfiType::UInt16 => quote! { u16 },
        FfiType::Int16 => quote! { i16 },
        FfiType::UInt32 => quote! { u32 },
        FfiType::Int32 => quote! { i32 },
        FfiType::UInt64 => quote! { napi::bindgen_prelude::BigInt },
        FfiType::Int64 => quote! { napi::bindgen_prelude::BigInt },
        FfiType::Float32 => quote! { f32 },
        FfiType::Float64 => quote! { f64 },
        FfiType::Handle => quote! { napi::bindgen_prelude::BigInt },
        FfiType::RustBuffer(_) | FfiType::ForeignBytes => {
            quote! { napi::bindgen_prelude::Buffer }
        }
        FfiType::RustCallStatus => quote! { RustCallStatus },
        FfiType::VoidPointer => quote! { napi::bindgen_prelude::BigInt },
        FfiType::Reference(_) | FfiType::MutReference(_) => {
            anyhow::bail!("The napi flavor does not support reference FFI types yet")
        }
        FfiType::Callback(_) | FfiType::Struct(_) => {
            anyhow::bail!("The napi flavor does not support callback/vtable FFI types yet")
        }
    })
}

fn ffi_type_rust(type_: &FfiType) -> Result<TokenStream> {
    Ok(match type_ {
        FfiType::UInt8 => quote! { u8 },
        FfiType::Int8 => quote! { i8 },
        FfiType::UInt16 => quote! { u16 },
        FfiType::Int16 => quote! { i16 },
        FfiType::UInt32 => quote! { u32 },
        FfiType::Int32 => quote! { i32 },
        FfiType::UInt64 => quote! { u64 },
        FfiType::Int64 => quote! { i64 },
        FfiType::Float32 => quote! { f32 },
        FfiType::Float64 => quote! { f64 },
        FfiType::Handle => quote! { u64 },
        FfiType::RustBuffer(_) | FfiType::ForeignBytes => quote! { uniffi::RustBuffer },
        FfiType::RustCallStatus => quote! { uniffi::RustCallStatus },
        FfiType::VoidPointer => quote! { uniffi::VoidPointer },
        FfiType::Reference(_) | FfiType::MutReference(_) => {
            anyhow::bail!("The napi flavor does not support reference FFI types yet")
        }
        FfiType::Callback(_) | FfiType::Struct(_) => {
            anyhow::bail!("The napi flavor does not support callback/vtable FFI types yet")
        }
    })
}
