/*
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/
 */

mod extensions;
mod util;

use anyhow::Result;
use proc_macro2::TokenStream;
use quote::{format_ident, quote};
use serde::{Deserialize, Serialize};
use syn::Ident;
use ubrn_common::CrateMetadata;
use uniffi_bindgen::{
    interface::{FfiArgument, FfiFunction, FfiType},
    ComponentInterface,
};
use util::{
    camel_case_ident, ident, if_or_default, if_then_map, map_or_default, snake_case_ident,
    upper_camel_ident,
};

use crate::{
    bindings::{
        extensions::{ComponentInterfaceExt as _, FfiCallbackFunctionExt as _},
        metadata::ModuleMetadata,
    },
    switches::SwitchArgs,
};

use self::extensions::{
    ComponentInterfaceExt as _, FfiCallbackFunction2, FfiDefinition2, FfiStruct2,
};

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub(crate) struct Config {}

#[allow(unused_variables)]
pub(crate) fn generate_rs(
    ci: &ComponentInterface,
    module: &ModuleMetadata,
    config: &Config,
    switches: &SwitchArgs,
    try_format_code: bool,
) -> Result<String> {
    let mut template = ComponentTemplate;

    let externs: TokenStream = ci
        .iter_ffi_functions_js_to_abi_rust()
        .map(|func| template.ffi_function_decl_c_abi(&func))
        .collect::<Result<_>>()?;

    let wrappers: TokenStream = ci
        .iter_ffi_functions_js_to_abi_rust()
        .map(|func| template.ffi_function(&func))
        .collect::<Result<_>>()?;

    let definitions: TokenStream = ci
        .ffi_definitions2()
        .map(|def| template.ffi_definition(&def))
        .collect::<Result<_>>()?;

    let prelude = runtime_prelude();

    let src = quote! {
        // Generated by uniffi-bindgen-react-native
        #prelude

        extern "C" {
            #externs
        }

        #wrappers

        #definitions
    };

    formatted(src, try_format_code)
}

pub(crate) fn generate_entrypoint(
    crate_: &CrateMetadata,
    modules: &[ModuleMetadata],
) -> Result<String> {
    let crate_ident = format_ident!("{}", crate_.library_name());
    let mods: Vec<_> = modules
        .iter()
        .map(|m| {
            let namespace = format_ident!("{}", m.rs_module());
            quote! { mod #namespace; }
        })
        .collect();

    let src = quote! {
        #[allow(unused_imports)]
        use #crate_ident;

        #(#mods)*
    };

    formatted(src, true)
}

fn formatted(tokens: TokenStream, try_format_code: bool) -> Result<String> {
    let code = if try_format_code {
        let syntax_tree = syn::parse2(tokens)?;
        prettyplease::unparse(&syntax_tree)
    } else {
        TokenStream::to_string(&tokens)
    };
    Ok(code)
}

fn runtime_prelude() -> TokenStream {
    quote! {
        use napi::bindgen_prelude::Env;
        use napi_derive::napi;

        mod js {
            use std::{
                cell::{Cell, RefCell},
                mem::ManuallyDrop,
                ptr::NonNull,
                sync::RwLock,
            };

            use napi::bindgen_prelude::{BigInt, Buffer, Env};
            use napi_derive::napi;

            pub mod uniffi {
                pub use uniffi_core::{
                    RustBuffer,
                    RustCallStatus,
                    RustCallStatusCode,
                    UniffiForeignPointerCell,
                };
                pub type VoidPointer = *const std::ffi::c_void;
            }

            pub trait IntoRust<HighLevel> {
                fn into_rust(v: HighLevel) -> Self;
            }

            pub trait IntoJs<HighLevel> {
                fn into_js(self) -> HighLevel;
            }

            macro_rules! identity_into_rust {
                ($high_level:ident, $rust_type:ty) => {
                    pub type $high_level = $rust_type;
                    impl IntoRust<$high_level> for $rust_type {
                        fn into_rust(v: $high_level) -> Self {
                            v
                        }
                    }
                    impl IntoJs<$high_level> for $rust_type {
                        fn into_js(self) -> $high_level {
                            self
                        }
                    }
                };
            }

            identity_into_rust!(UInt8, u8);
            identity_into_rust!(UInt16, u16);
            identity_into_rust!(UInt32, u32);
            identity_into_rust!(Int8, i8);
            identity_into_rust!(Int16, i16);
            identity_into_rust!(Int32, i32);
            identity_into_rust!(Float32, f32);
            identity_into_rust!(Float64, f64);

            // N-API numbers are represented as f64, but some generated foreign-future
            // structs contain Float32 payload fields.
            impl IntoRust<Float64> for f32 {
                fn into_rust(v: Float64) -> Self {
                    v as f32
                }
            }

            impl IntoJs<Float64> for f32 {
                fn into_js(self) -> Float64 {
                    self as f64
                }
            }

            pub type UInt64 = BigInt;
            pub type Int64 = BigInt;
            pub type Handle = UInt64;
            pub type VoidPointer = BigInt;
            pub type ForeignBytes = Buffer;

            impl IntoRust<UInt64> for u64 {
                fn into_rust(v: UInt64) -> Self {
                    let (is_negative, value, _lossless) = v.get_u64();
                    if is_negative {
                        panic!("Expected non-negative bigint value");
                    }
                    value
                }
            }

            impl IntoJs<UInt64> for u64 {
                fn into_js(self) -> UInt64 {
                    BigInt::from(self)
                }
            }

            impl IntoRust<Int64> for i64 {
                fn into_rust(v: Int64) -> Self {
                    let (value, _lossless) = v.get_i64();
                    value
                }
            }

            impl IntoJs<Int64> for i64 {
                fn into_js(self) -> Int64 {
                    BigInt::from(self)
                }
            }

            impl IntoRust<VoidPointer> for uniffi::VoidPointer {
                fn into_rust(v: VoidPointer) -> Self {
                    <u64 as IntoRust<UInt64>>::into_rust(v) as Self
                }
            }

            impl IntoJs<VoidPointer> for uniffi::VoidPointer {
                fn into_js(self) -> VoidPointer {
                    <u64 as IntoJs<UInt64>>::into_js(self as u64)
                }
            }

            impl IntoRust<ForeignBytes> for uniffi::RustBuffer {
                fn into_rust(v: ForeignBytes) -> Self {
                    Self::from_vec(v.to_vec())
                }
            }

            impl IntoJs<ForeignBytes> for uniffi::RustBuffer {
                fn into_js(self) -> ForeignBytes {
                    Buffer::from(self.destroy_into_vec())
                }
            }

            fn read_result_status(code: Option<i8>, error_buf: Option<&Buffer>) -> uniffi::RustCallStatus {
                let code = code.unwrap_or(0);
                let code = uniffi::RustCallStatusCode::try_from(code)
                    .expect("Unexpected error code. This is likely a bug in UBRN");
                let bytes = error_buf.map(|buf| buf.to_vec()).unwrap_or_default();
                let error_buf = std::mem::ManuallyDrop::new(uniffi::RustBuffer::from_vec(bytes));
                uniffi::RustCallStatus { error_buf, code }
            }

            macro_rules! uniffi_result_void {
                ($name:ident) => {
                    #[napi(object)]
                    pub struct $name {
                        pub code: Option<i8>,
                        #[napi(js_name = "errorBuf")]
                        pub error_buf: Option<Buffer>,
                    }

                    impl $name {
                        pub fn copy_into_status(&self, rust: &mut uniffi::RustCallStatus) {
                            *rust = read_result_status(self.code, self.error_buf.as_ref());
                        }
                    }
                };
            }

            macro_rules! uniffi_result_with_return {
                ($name:ident, $pointee_ty:ty, $rust_ty:ty, $default_expr:expr, $convert:expr) => {
                    #[napi(object)]
                    pub struct $name {
                        pub code: Option<i8>,
                        #[napi(js_name = "errorBuf")]
                        pub error_buf: Option<Buffer>,
                        pub pointee: Option<$pointee_ty>,
                    }

                    impl $name {
                        pub fn copy_into_status(&self, rust: &mut uniffi::RustCallStatus) {
                            *rust = read_result_status(self.code, self.error_buf.as_ref());
                        }

                        pub fn copy_into_return(&self, rust: &mut $rust_ty) {
                            let value = self
                                .pointee
                                .as_ref()
                                .map(|value| ($convert)(value))
                                .unwrap_or_else(|| $default_expr);
                            *rust = value;
                        }
                    }
                };
            }

            uniffi_result_void!(UniffiResultVoid);
            uniffi_result_with_return!(UniffiResultUInt8, u8, u8, 0u8, |v: &u8| *v);
            uniffi_result_with_return!(UniffiResultUInt16, u16, u16, 0u16, |v: &u16| *v);
            uniffi_result_with_return!(UniffiResultUInt32, u32, u32, 0u32, |v: &u32| *v);
            uniffi_result_with_return!(UniffiResultUInt64, BigInt, u64, 0u64, |v: &BigInt| {
                let (is_negative, value, _lossless) = v.get_u64();
                if is_negative {
                    panic!("Expected non-negative bigint value");
                }
                value
            });
            uniffi_result_with_return!(UniffiResultInt8, i8, i8, 0i8, |v: &i8| *v);
            uniffi_result_with_return!(UniffiResultInt16, i16, i16, 0i16, |v: &i16| *v);
            uniffi_result_with_return!(UniffiResultInt32, i32, i32, 0i32, |v: &i32| *v);
            uniffi_result_with_return!(UniffiResultInt64, BigInt, i64, 0i64, |v: &BigInt| {
                let (value, _lossless) = v.get_i64();
                value
            });
            uniffi_result_with_return!(UniffiResultFloat32, f64, f32, 0.0f32, |v: &f64| *v as f32);
            uniffi_result_with_return!(UniffiResultFloat64, f64, f64, 0.0f64, |v: &f64| *v);
            uniffi_result_with_return!(
                UniffiResultForeignBytes,
                Buffer,
                uniffi::RustBuffer,
                uniffi::RustBuffer::from_vec(Vec::<u8>::new()),
                |v: &Buffer| {
                    uniffi::RustBuffer::from_vec(v.to_vec())
                }
            );

            thread_local! {
                static CURRENT_ENV: Cell<napi::sys::napi_env> = const { Cell::new(std::ptr::null_mut()) };
            }

            fn env_to_raw(env: Env) -> napi::sys::napi_env {
                env.raw()
            }

            pub fn set_current_env(env: Env) {
                let raw = env_to_raw(env);
                CURRENT_ENV.with(|cell| cell.set(raw));
            }

            pub fn current_env() -> Env {
                CURRENT_ENV.with(|cell| {
                    let raw = cell.get();
                    assert!(
                        !raw.is_null(),
                        "N-API Env accessed before it was initialized. This is a bug in UBRN"
                    );
                    Env::from_raw(raw)
                })
            }

            #[napi]
            #[derive(Default)]
            pub struct RustCallStatus {
                pub code: i8,
                error_buf: Option<Vec<u8>>,
            }

            #[napi]
            impl RustCallStatus {
                #[napi(constructor)]
                pub fn new() -> Self {
                    Default::default()
                }

                #[napi(getter, js_name = "errorBuf")]
                pub fn get_error_buf(&self) -> Option<Buffer> {
                    self.error_buf.as_ref().map(|bytes| Buffer::from(bytes.clone()))
                }

                #[napi(setter, js_name = "errorBuf")]
                pub fn set_error_buf(&mut self, error_buf: Option<Buffer>) {
                    self.error_buf = error_buf.map(|buf| buf.to_vec());
                }

                pub fn from_object(object: napi::bindgen_prelude::Object<'_>) -> Self {
                    let code = object
                        .get("code")
                        .expect("Failed reading RustCallStatus.code from N-API object")
                        .unwrap_or_default();
                    let error_buf = match object.get::<Buffer>("errorBuf") {
                        Ok(value) => value.map(|buf| buf.to_vec()),
                        Err(_) => match object
                            .get::<napi::bindgen_prelude::Uint8Array>("errorBuf")
                        {
                            Ok(value) => value.map(|bytes| bytes.to_vec()),
                            Err(_) => None,
                        },
                    };
                    Self { code, error_buf }
                }
            }

            impl RustCallStatus {
                pub fn copy_from(&mut self, rust: uniffi::RustCallStatus) {
                    self.code = rust.code as i8;
                    let buf = std::mem::ManuallyDrop::into_inner(rust.error_buf).destroy_into_vec();
                    self.error_buf = Some(buf);
                }
            }

            impl IntoRust<RustCallStatus> for uniffi::RustCallStatus {
                fn into_rust(js: RustCallStatus) -> Self {
                    let code = uniffi::RustCallStatusCode::try_from(js.code)
                        .expect("Unexpected error code. This is likely a bug in UBRN");
                    let bytes = js.error_buf.unwrap_or_default();
                    let error_buf = std::mem::ManuallyDrop::new(uniffi::RustBuffer::from_vec(bytes));
                    uniffi::RustCallStatus { error_buf, code }
                }
            }

            impl IntoJs<RustCallStatus> for uniffi::RustCallStatus {
                fn into_js(self) -> RustCallStatus {
                    let mut status = RustCallStatus::new();
                    status.copy_from(self);
                    status
                }
            }

            pub struct ForeignCell<T> {
                inner: RefCell<Option<ManuallyDrop<T>>>,
            }

            impl<T> ForeignCell<T> {
                pub fn new() -> Self {
                    Self {
                        inner: RefCell::new(None),
                    }
                }

                pub fn set(&self, value: T) {
                    self.inner.replace(Some(ManuallyDrop::new(value)));
                }

                pub fn with_value<F, R>(&self, f: F) -> R
                where
                    F: FnOnce(&T) -> R,
                {
                    let value = self.inner.borrow();
                    let value = value
                        .as_ref()
                        .expect("ForeignCell accessed before initialization");
                    // SAFETY: `ManuallyDrop<T>` has the same layout as `T`.
                    let value: &T = unsafe {
                        &*(value as *const ManuallyDrop<T> as *const T)
                    };
                    f(value)
                }
            }

            impl<T> Default for ForeignCell<T> {
                fn default() -> Self {
                    Self::new()
                }
            }

            pub struct SharedCell<T> {
                inner: RwLock<Option<ManuallyDrop<T>>>,
            }

            impl<T> SharedCell<T> {
                pub const fn new() -> Self {
                    Self {
                        inner: RwLock::new(None),
                    }
                }

                pub fn set(&self, value: T) {
                    let mut guard = self
                        .inner
                        .write()
                        .expect("SharedCell lock poisoned while setting callback");
                    *guard = Some(ManuallyDrop::new(value));
                }

                pub fn with_value<F, R>(&self, f: F) -> R
                where
                    F: FnOnce(&T) -> R,
                {
                    let guard = self
                        .inner
                        .read()
                        .expect("SharedCell lock poisoned while reading callback");
                    let value = guard
                        .as_ref()
                        .expect("SharedCell accessed before initialization");
                    // SAFETY: `ManuallyDrop<T>` has the same layout as `T`.
                    let value: &T = unsafe {
                        &*(value as *const ManuallyDrop<T> as *const T)
                    };
                    f(value)
                }
            }

            impl<T> Default for SharedCell<T> {
                fn default() -> Self {
                    Self::new()
                }
            }

            impl<JsType, RsType> IntoRust<JsType> for NonNull<RsType>
            where
                RsType: IntoRust<JsType>,
            {
                fn into_rust(js: JsType) -> Self {
                    let rs = RsType::into_rust(js);
                    let ptr = Box::into_raw(Box::new(rs));
                    // SAFETY: Box::into_raw never returns null.
                    unsafe { NonNull::new_unchecked(ptr) }
                }
            }
        }

        use js::{IntoJs, IntoRust};
    }
}

struct ComponentTemplate;

impl ComponentTemplate {
    fn ffi_definition(&mut self, definition: &FfiDefinition2) -> Result<TokenStream> {
        match definition {
            FfiDefinition2::CallbackFunction(cb) => self.ffi_callback(cb),
            FfiDefinition2::FunctionLiteral(cb) => self.ffi_function_literal(cb),
            FfiDefinition2::Struct(st) => self.ffi_struct(st),
        }
    }

    fn ffi_function_decl_c_abi(&mut self, func: &FfiFunction) -> Result<TokenStream> {
        let func_ident = ident(func.name());
        let args_decl = self.arg_list_decl(&func.arguments(), |t| self.ffi_type_rust(t))?;
        let decl_suffix = if let Some(type_) = func.return_type() {
            let return_type = self.ffi_type_rust(type_)?;
            quote! { -> #return_type }
        } else {
            quote! {}
        };

        let call_status = if_then_map(func.has_rust_call_status_arg(), || {
            quote! { status_: &mut js::uniffi::RustCallStatus }
        });

        Ok(quote! {
            fn #func_ident(#args_decl #call_status) #decl_suffix;
        })
    }

    fn ffi_function(&mut self, func: &FfiFunction) -> Result<TokenStream> {
        let func_ident = ident(func.name());
        let foreign_func_ident = ident(&format!("ubrn_{}", func.name()));
        let js_name = syn::LitStr::new(
            &foreign_func_ident.to_string(),
            proc_macro2::Span::call_site(),
        );
        let annotation = quote! { #[napi(js_name = #js_name)] };

        let args = func.arguments();
        let js_args_decl = self.arg_list_decl(&args, |t| self.ffi_type_foreign_to_rust(t))?;
        let args_into_rust: TokenStream =
            self.arg_list_convert(&args, |ident, type_| self.convert_to_rust(ident, type_))?;

        let has_return = func.return_type().is_some();

        let decl_suffix = if let Some(type_) = func.return_type() {
            let return_type = self.ffi_type_foreign(type_)?;
            quote! { -> #return_type }
        } else {
            quote! {}
        };

        let needs_call_status = func.has_rust_call_status_arg();
        if needs_call_status {
            let rust_status_ident = ident("u_status_");
            let foreign_status_ident = ident("f_status_");
            let return_ident = ident("value_");
            let ArgumentTokens {
                declaration: let_value,
                returns: return_value,
            } = if_or_default(
                has_return,
                ArgumentTokens {
                    declaration: quote! { let #return_ident = },
                    returns: quote! { #return_ident.into_js() },
                },
            );

            Ok(quote! {
                #annotation
                pub fn #foreign_func_ident(env_: Env, #js_args_decl #foreign_status_ident: &mut js::RustCallStatus) #decl_suffix {
                    js::set_current_env(env_);
                    let mut #rust_status_ident = js::uniffi::RustCallStatus::default();
                    #let_value unsafe { #func_ident(#args_into_rust &mut #rust_status_ident) };
                    #foreign_status_ident.copy_from(#rust_status_ident);
                    #return_value
                }
            })
        } else {
            if has_return {
                Ok(quote! {
                    #annotation
                    pub fn #foreign_func_ident(env_: Env, #js_args_decl) #decl_suffix {
                        js::set_current_env(env_);
                        unsafe { #func_ident(#args_into_rust) }.into_js()
                    }
                })
            } else {
                Ok(quote! {
                    #annotation
                    pub fn #foreign_func_ident(env_: Env, #js_args_decl) {
                        js::set_current_env(env_);
                        unsafe { #func_ident(#args_into_rust) };
                    }
                })
            }
        }
    }

    fn ffi_function_literal(&mut self, cb: &FfiCallbackFunction2) -> Result<TokenStream> {
        let args = cb.callback().arguments();
        let js_args_decl = self.arg_list_decl(&args, |t| self.ffi_type_foreign_to_rust(t))?;
        let args_into_rust: TokenStream =
            self.arg_list_convert(&args, |ident, type_| self.convert_to_rust(ident, type_))?;
        let rust_args_decl: TokenStream = self.arg_list_decl(&args, |t| self.ffi_type_rust(t))?;

        let module_ident = cb.module_ident();
        let callback_type_alias_ident = callback_fn_ident();
        let callback_struct_ident = upper_camel_ident(&format!("{}_js_callback_fn", module_ident));

        Ok(quote! {
            mod #module_ident {
                use super::*;

                #[napi]
                pub struct #callback_struct_ident {
                    callback: FnSig,
                }

                impl #callback_struct_ident {
                    fn new(callback: FnSig) -> Self {
                        Self { callback }
                    }
                }

                #[napi]
                impl #callback_struct_ident {
                    #[napi]
                    pub fn call(&self,
                        _ctx: napi::bindgen_prelude::Unknown,
                        #js_args_decl
                    ) {
                        (self.callback)(#args_into_rust)
                    }
                }

                pub(super) type FnSig = extern "C" fn(#rust_args_decl);
                pub(super) type #callback_type_alias_ident = #callback_struct_ident;

                impl IntoJs<#callback_type_alias_ident> for FnSig {
                    fn into_js(self) -> #callback_type_alias_ident {
                        #callback_struct_ident::new(self)
                    }
                }
            }
        })
    }

    fn ffi_callback(&mut self, cb: &FfiCallbackFunction2) -> Result<TokenStream> {
        let callback_fn_ident = callback_fn_ident();

        let result_ident = ident("uniffi_result_");
        let return_type = if cb.has_return_out_param() {
            let rt = cb.return_type();
            let rs_ret_name = if rt.is_some() {
                "rs_return_"
            } else {
                "_rs_return"
            };
            let rs_ret_ident = ident(rs_ret_name);
            let rs_return_type = self.ffi_type_rust_out_param(rt.as_ref())?;
            let declaration = quote! {
                #rs_ret_ident: &mut #rs_return_type,
            };
            let returns = map_or_default(rt.as_ref(), |_| {
                quote! {
                    #result_ident.copy_into_return(#rs_ret_ident);
                }
            });
            ArgumentTokens {
                declaration,
                returns,
            }
        } else {
            ArgumentTokens::default()
        };

        let call_status = if_then_map(cb.callback().has_rust_call_status_arg(), || {
            let rs_call_status = ident("rs_call_status_");
            ArgumentTokens {
                declaration: quote! {
                    #rs_call_status: &mut js::uniffi::RustCallStatus,
                },
                returns: quote! {
                    #result_ident.copy_into_status(#rs_call_status);
                },
            }
        });

        let args: Vec<_> = cb.callback().arguments_no_return().collect();
        let rust_args_decl: TokenStream = self.arg_list_decl(&args, |t| self.ffi_type_rust(t))?;
        let args_into_js: Vec<TokenStream> = args
            .iter()
            .map(|arg| {
                let arg_ident = ident(arg.name());
                self.convert_to_js(quote! { #arg_ident }, &arg.type_())
            })
            .collect::<Result<_>>()?;

        let js_arg_types: Vec<TokenStream> = args
            .iter()
            .map(|arg| self.ffi_type_foreign(&arg.type_()))
            .collect::<Result<_>>()?;

        let direct_return: Option<FfiType> = cb
            .callback()
            .return_type()
            .cloned()
            .filter(|_| !cb.has_return_out_param());

        let js_return_type = if direct_return.is_some() {
            let rt = direct_return.as_ref().expect("checked above");
            self.ffi_type_foreign(rt)?
        } else if cb.callback().returns_result() {
            self.ffi_type_uniffi_result(cb.callback().arg_return_type().as_ref())?
        } else {
            quote! { () }
        };

        let fn_return_suffix = if let Some(rt) = direct_return.as_ref() {
            let rust_return = self.ffi_type_rust(rt)?;
            quote! { -> #rust_return }
        } else {
            quote! {}
        };

        let direct_return_expr = if let Some(rt) = direct_return.as_ref() {
            let rust_return = self.ffi_type_rust(rt)?;
            quote! { #rust_return::into_rust(#result_ident) }
        } else {
            quote! {}
        };

        let return_let = if_or_default(
            cb.callback().has_rust_call_status_arg()
                || cb.return_type().is_some()
                || direct_return.is_some(),
            quote! {
                let #result_ident =
            },
        );

        let ArgumentTokens {
            declaration: call_status_arg_decl,
            returns: call_status_copy,
        } = call_status;

        let ArgumentTokens {
            declaration: return_arg_decl,
            returns: return_copy,
        } = return_type;

        let callback_tuple_args = tuple_type(&js_arg_types);
        let callback_call_args = tuple_expr(args_into_js.as_slice());

        let cell = ident("cell_");
        let callback = ident("callback_");
        let inner = if cb.callback().is_blocking() {
            quote! {
                use super::*;

                pub(super) struct #callback_fn_ident(
                    napi::bindgen_prelude::FunctionRef<
                        napi::bindgen_prelude::FnArgs<#callback_tuple_args>,
                        #js_return_type
                    >
                );

                impl #callback_fn_ident {
                    fn call(&self, args: #callback_tuple_args) -> #js_return_type {
                        let env_ = js::current_env();
                        let callback_ = self.0
                            .borrow_back(&env_)
                            .expect("Failed to borrow N-API callback reference");
                        callback_
                            .call(napi::bindgen_prelude::FnArgs::from(args))
                            .expect("N-API callback call failed")
                    }
                }

                impl napi::bindgen_prelude::FromNapiValue for #callback_fn_ident {
                    unsafe fn from_napi_value(
                        env: napi::sys::napi_env,
                        value: napi::sys::napi_value
                    ) -> napi::bindgen_prelude::Result<Self> {
                        let callback =
                            <napi::bindgen_prelude::FunctionRef<
                                napi::bindgen_prelude::FnArgs<#callback_tuple_args>,
                                #js_return_type
                            > as napi::bindgen_prelude::FromNapiValue>::from_napi_value(env, value)?;
                        Ok(Self(callback))
                    }
                }

                thread_local! {
                    static CALLBACK: js::ForeignCell<#callback_fn_ident> = js::ForeignCell::new();
                }

                impl IntoRust<#callback_fn_ident> for FnSig {
                    fn into_rust(callback: #callback_fn_ident) -> Self {
                        CALLBACK.with(|cell| cell.set(callback));
                        implementation
                    }
                }

                pub(super) type FnSig = extern "C" fn(#rust_args_decl #return_arg_decl #call_status_arg_decl) #fn_return_suffix;

                extern "C" fn implementation(#rust_args_decl #return_arg_decl #call_status_arg_decl) #fn_return_suffix {
                    #return_let CALLBACK.with(|#cell| #cell.with_value(|#callback| {
                        #callback.call(#callback_call_args)
                    }));
                    #call_status_copy
                    #return_copy
                    #direct_return_expr
                }
            }
        } else {
            quote! {
                use super::*;

                pub(super) struct #callback_fn_ident(
                    std::sync::Arc<napi::threadsafe_function::ThreadsafeFunction<
                        napi::bindgen_prelude::FnArgs<#callback_tuple_args>,
                        (),
                        napi::bindgen_prelude::FnArgs<#callback_tuple_args>,
                        napi::Status,
                        false,
                        true
                    >>
                );

                impl #callback_fn_ident {
                    fn call(&self, args: #callback_tuple_args) {
                        let status = self.0.call(
                            napi::bindgen_prelude::FnArgs::from(args),
                            napi::threadsafe_function::ThreadsafeFunctionCallMode::NonBlocking
                        );
                        if status != napi::Status::Ok {
                            panic!("N-API ThreadsafeFunction call failed with status: {status:?}");
                        }
                    }
                }

                impl napi::bindgen_prelude::FromNapiValue for #callback_fn_ident {
                    unsafe fn from_napi_value(
                        env: napi::sys::napi_env,
                        value: napi::sys::napi_value
                    ) -> napi::bindgen_prelude::Result<Self> {
                        let callback = <napi::threadsafe_function::ThreadsafeFunction<
                            napi::bindgen_prelude::FnArgs<#callback_tuple_args>,
                            (),
                            napi::bindgen_prelude::FnArgs<#callback_tuple_args>,
                            napi::Status,
                            false,
                            true
                        > as napi::bindgen_prelude::FromNapiValue>::from_napi_value(env, value)?;
                        Ok(Self(std::sync::Arc::new(callback)))
                    }
                }

                static CALLBACK: js::SharedCell<#callback_fn_ident> = js::SharedCell::new();

                impl IntoRust<#callback_fn_ident> for FnSig {
                    fn into_rust(callback: #callback_fn_ident) -> Self {
                        CALLBACK.set(callback);
                        implementation
                    }
                }

                pub(super) type FnSig = extern "C" fn(#rust_args_decl #return_arg_decl #call_status_arg_decl) #fn_return_suffix;

                extern "C" fn implementation(#rust_args_decl #return_arg_decl #call_status_arg_decl) #fn_return_suffix {
                    #return_let CALLBACK.with_value(|#callback| {
                        #callback.call(#callback_call_args)
                    });
                    #call_status_copy
                    #return_copy
                    #direct_return_expr
                }
            }
        };

        let cb_ident = cb.module_ident();
        let non_snake_case = if_or_default(
            cb.callback().is_free_callback(),
            quote! {
                #[allow(non_snake_case)]
            },
        );

        Ok(quote! {
            #non_snake_case
            mod #cb_ident {
                #inner
            }
        })
    }

    fn ffi_struct(&self, st: &FfiStruct2) -> Result<TokenStream> {
        let module_name = st.module_ident();

        let vtable_rs_fields = st
            .fields()
            .map(|f| {
                let field_name = f.name();
                let field_type = if st.is_callback_method(field_name) {
                    let alias_ident = st.method_alias_ident(field_name);
                    Ok(quote! { #alias_ident::FnSig })
                } else {
                    self.ffi_type_rust(&f.type_())
                };
                let field_name = ident(field_name);
                let field_type = field_type?;
                Ok(quote! { #field_name: #field_type, })
            })
            .collect::<Result<TokenStream>>()?;

        let vtable_js_getters = st
            .fields()
            .map(|field| {
                let field_name = field.name();
                let field_ident = ident(field_name);
                let js_field_name = camel_case_ident(field_name).to_string();
                let js_field_name =
                    syn::LitStr::new(&js_field_name, proc_macro2::Span::call_site());
                if st.is_callback_method(field_name) {
                    let callback_fn_ident = callback_fn_ident();
                    let alias_ident = st.method_alias_ident(field_name);
                    Ok(quote! {
                        fn #field_ident(&self) -> #alias_ident::#callback_fn_ident {
                            self.object()
                                .get(#js_field_name)
                                .expect("Failed reading callback field from N-API object")
                                .expect("Missing callback field from N-API object")
                        }
                    })
                } else if matches!(field.type_(), FfiType::RustCallStatus) {
                    Ok(quote! {
                        fn #field_ident(&self) -> napi::bindgen_prelude::Object<'_> {
                            self.object()
                                .get(#js_field_name)
                                .expect("Failed reading struct field from N-API object")
                                .expect("Missing struct field from N-API object")
                        }
                    })
                } else {
                    let field_type = field.type_();
                    let type_ = self.ffi_type_foreign_future(&field_type)?;
                    Ok(quote! {
                        fn #field_ident(&self) -> #type_ {
                            self.object()
                                .get(#js_field_name)
                                .expect("Failed reading struct field from N-API object")
                                .expect("Missing struct field from N-API object")
                        }
                    })
                }
            })
            .collect::<Result<TokenStream>>()?;

        let into_rust_block = {
            let from_ident = ident("v_");
            let from_fields = st
                .fields()
                .map(|field| {
                    let field_name = field.name();
                    let field_ident = ident(field_name);
                    if st.is_callback_method(field_name) {
                        let alias_ident = st.method_alias_ident(field_name);
                        Ok(quote! {
                            #field_ident: #alias_ident::FnSig::into_rust(#from_ident.#field_ident()),
                        })
                    } else if matches!(field.type_(), FfiType::RustCallStatus) {
                        Ok(quote! {
                            #field_ident: js::uniffi::RustCallStatus::into_rust(
                                js::RustCallStatus::from_object(#from_ident.#field_ident())
                            ),
                        })
                    } else {
                        let rust_type = self.ffi_type_rust(&field.type_())?;
                        Ok(quote! {
                            #field_ident: #rust_type::into_rust(#from_ident.#field_ident()),
                        })
                    }
                })
                .collect::<Result<TokenStream>>()?;
            quote! {
                impl IntoRust<VTableJs> for VTableRs {
                    fn into_rust(#from_ident: VTableJs) -> Self {
                        Self {
                            #from_fields
                        }
                    }
                }
            }
        };

        let copy_into_block = if_then_map(st.is_passed_from_js_to_rust(), || {
            quote! {
                impl VTableJs {
                    #[allow(unused)]
                    pub(super) fn copy_into_return(self, rust: &mut VTableRs) {
                        *rust = <VTableRs>::into_rust(self);
                    }
                }
            }
        });

        let use_statements: TokenStream = st
            .method_names()
            .map(|name| {
                let mod_ident = st.method_mod_ident(name);
                let alias_ident = st.method_alias_ident(name);
                quote! {
                    use super::#mod_ident as #alias_ident;
                }
            })
            .collect();

        Ok(quote! {
            mod #module_name {
                use super::*;
                #use_statements

                pub(super) struct VTableJs {
                    env: napi::sys::napi_env,
                    value: napi::sys::napi_value,
                }

                impl napi::bindgen_prelude::FromNapiValue for VTableJs {
                    unsafe fn from_napi_value(
                        env: napi::sys::napi_env,
                        value: napi::sys::napi_value
                    ) -> napi::bindgen_prelude::Result<Self> {
                        Ok(Self { env, value })
                    }
                }

                impl VTableJs {
                    fn object(&self) -> napi::bindgen_prelude::Object<'_> {
                        napi::bindgen_prelude::Object::from_raw(self.env, self.value)
                    }

                    #vtable_js_getters
                }

                #[repr(C)]
                pub(super) struct VTableRs {
                    #vtable_rs_fields
                }

                #into_rust_block
                #copy_into_block
            }
        })
    }

    fn arg_list_decl<F>(&self, args: &[&FfiArgument], func: F) -> Result<TokenStream>
    where
        F: Fn(&FfiType) -> Result<TokenStream>,
    {
        args.iter().map(|arg| self.arg_decl(arg, &func)).collect()
    }

    fn arg_list_convert<F>(&self, args: &[&FfiArgument], func: F) -> Result<TokenStream>
    where
        F: Fn(Ident, &FfiType) -> Result<TokenStream>,
    {
        args.iter()
            .map(|arg| func(ident(arg.name()), &arg.type_()))
            .collect()
    }

    fn arg_decl<F>(&self, arg: &FfiArgument, func: F) -> Result<TokenStream>
    where
        F: Fn(&FfiType) -> Result<TokenStream>,
    {
        let ident = self.arg_ident(arg);
        let typ = func(&arg.type_())?;
        Ok(quote! { #ident: #typ, })
    }

    fn convert_to_rust(&self, ident: Ident, type_: &FfiType) -> Result<TokenStream> {
        let rust_type = self.ffi_type_rust(type_)?;
        Ok(match type_ {
            FfiType::UInt64 | FfiType::Handle => {
                quote! { <u64 as IntoRust<js::UInt64>>::into_rust(#ident), }
            }
            FfiType::Int64 => quote! { <i64 as IntoRust<js::Int64>>::into_rust(#ident), },
            FfiType::RustBuffer(_) | FfiType::ForeignBytes => {
                quote! { <js::uniffi::RustBuffer as IntoRust<js::ForeignBytes>>::into_rust(#ident), }
            }
            FfiType::VoidPointer => {
                quote! { <js::uniffi::VoidPointer as IntoRust<js::VoidPointer>>::into_rust(#ident), }
            }
            FfiType::Reference(inner) | FfiType::MutReference(inner) => {
                let inner_rust = self.ffi_type_rust(inner)?;
                let inner_js = self.ffi_type_foreign_to_rust(inner)?;
                quote! { <std::ptr::NonNull<#inner_rust> as IntoRust<#inner_js>>::into_rust(#ident), }
            }
            FfiType::Callback(_) | FfiType::Struct(_) => quote! { #rust_type::into_rust(#ident), },
            _ => quote! { #ident, },
        })
    }

    fn convert_to_js(&self, value: TokenStream, type_: &FfiType) -> Result<TokenStream> {
        Ok(match type_ {
            FfiType::UInt64 | FfiType::Handle => {
                quote! { <u64 as IntoJs<js::UInt64>>::into_js(#value) }
            }
            FfiType::Int64 => quote! { <i64 as IntoJs<js::Int64>>::into_js(#value) },
            FfiType::RustBuffer(_) | FfiType::ForeignBytes => {
                quote! { <js::uniffi::RustBuffer as IntoJs<js::ForeignBytes>>::into_js(#value) }
            }
            FfiType::VoidPointer => {
                quote! { <js::uniffi::VoidPointer as IntoJs<js::VoidPointer>>::into_js(#value) }
            }
            FfiType::Callback(_) | FfiType::Struct(_) => quote! { #value.into_js() },
            FfiType::Reference(_) | FfiType::MutReference(_) => {
                anyhow::bail!("The napi flavor does not support reference FFI return types yet")
            }
            _ => value,
        })
    }

    fn arg_ident(&self, arg: &FfiArgument) -> Ident {
        ident(arg.name())
    }

    fn ffi_type_foreign_to_rust(&self, t: &FfiType) -> Result<TokenStream> {
        match t {
            FfiType::Reference(t) | FfiType::MutReference(t) => self.ffi_type_foreign(t),
            _ => self.ffi_type_foreign(t),
        }
    }

    fn ffi_type_uniffi_result(&self, t: Option<&FfiType>) -> Result<TokenStream> {
        Ok(match t {
            None => quote! { js::UniffiResultVoid },
            Some(t) => match t {
                FfiType::UInt8 => quote! { js::UniffiResultUInt8 },
                FfiType::UInt16 => quote! { js::UniffiResultUInt16 },
                FfiType::UInt32 => quote! { js::UniffiResultUInt32 },
                FfiType::UInt64 => quote! { js::UniffiResultUInt64 },
                FfiType::Int8 => quote! { js::UniffiResultInt8 },
                FfiType::Int16 => quote! { js::UniffiResultInt16 },
                FfiType::Int32 => quote! { js::UniffiResultInt32 },
                FfiType::Int64 => quote! { js::UniffiResultInt64 },
                FfiType::Float32 => quote! { js::UniffiResultFloat32 },
                FfiType::Float64 => quote! { js::UniffiResultFloat64 },
                FfiType::Handle => quote! { js::UniffiResultUInt64 },
                FfiType::RustBuffer(_) | FfiType::ForeignBytes => {
                    quote! { js::UniffiResultForeignBytes }
                }
                FfiType::VoidPointer => quote! { js::UniffiResultVoid },
                FfiType::Struct(s) => {
                    let module_ident = snake_case_ident(s);
                    quote! { #module_ident::VTableJs }
                }
                FfiType::Reference(t) | FfiType::MutReference(t) => {
                    self.ffi_type_uniffi_result(Some(t))?
                }
                _ => unreachable!("Uniffi doesn't support returning {t:?} from callbacks"),
            },
        })
    }

    fn ffi_type_foreign_future(&self, t: &FfiType) -> Result<TokenStream> {
        match t {
            FfiType::Reference(t) => self.ffi_type_foreign(t),
            FfiType::Float32 => Ok(quote! { js::Float64 }),
            _ => self.ffi_type_foreign(t),
        }
    }

    fn ffi_type_foreign(&self, t: &FfiType) -> Result<TokenStream> {
        Ok(match t {
            FfiType::UInt8 => quote! { js::UInt8 },
            FfiType::Int8 => quote! { js::Int8 },
            FfiType::UInt16 => quote! { js::UInt16 },
            FfiType::Int16 => quote! { js::Int16 },
            FfiType::UInt32 => quote! { js::UInt32 },
            FfiType::Int32 => quote! { js::Int32 },
            FfiType::UInt64 => quote! { js::UInt64 },
            FfiType::Int64 => quote! { js::Int64 },
            FfiType::Float32 => quote! { js::Float32 },
            FfiType::Float64 => quote! { js::Float64 },
            FfiType::Handle => quote! { js::Handle },
            FfiType::ForeignBytes => quote! { js::ForeignBytes },
            FfiType::RustBuffer(_) => quote! { js::ForeignBytes },
            FfiType::RustCallStatus => quote! { js::RustCallStatus },
            FfiType::VoidPointer => quote! { js::VoidPointer },
            FfiType::Struct(s) => {
                let mod_ident = snake_case_ident(s);
                quote! { #mod_ident::VTableJs }
            }
            FfiType::Callback(cb) => {
                let mod_ident = snake_case_ident(cb);
                let callback_fn_ident = callback_fn_ident();
                quote! { #mod_ident::#callback_fn_ident }
            }
            FfiType::Reference(_) | FfiType::MutReference(_) => {
                unreachable!("FfiType::Reference should be unpacked by a wrapper function");
            }
        })
    }

    fn ffi_type_rust_out_param(&self, t: Option<&FfiType>) -> Result<TokenStream> {
        match t {
            Some(FfiType::Reference(t)) | Some(FfiType::MutReference(t)) => self.ffi_type_rust(t),
            Some(t) => self.ffi_type_rust(t),
            None => Ok(quote! { () }),
        }
    }

    fn ffi_type_rust(&self, t: &FfiType) -> Result<TokenStream> {
        Ok(match t {
            FfiType::UInt8 => quote! { u8 },
            FfiType::Int8 => quote! { i8 },
            FfiType::UInt16 => quote! { u16 },
            FfiType::Int16 => quote! { i16 },
            FfiType::UInt32 => quote! { u32 },
            FfiType::Int32 => quote! { i32 },
            FfiType::UInt64 => quote! { u64 },
            FfiType::Int64 => quote! { i64 },
            FfiType::Float32 => quote! { f32 },
            FfiType::Float64 => quote! { f64 },
            FfiType::Handle => quote! { u64 },
            FfiType::ForeignBytes => quote! { js::uniffi::RustBuffer },
            FfiType::RustBuffer(_) => quote! { js::uniffi::RustBuffer },
            FfiType::RustCallStatus => quote! { js::uniffi::RustCallStatus },
            FfiType::VoidPointer => quote! { js::uniffi::VoidPointer },
            FfiType::Struct(s) => {
                let mod_ident = snake_case_ident(s);
                quote! { #mod_ident::VTableRs }
            }
            FfiType::Callback(cb) => {
                let mod_ident = snake_case_ident(cb);
                quote! { #mod_ident::FnSig }
            }
            FfiType::Reference(t) | FfiType::MutReference(t) => {
                let typ = self.ffi_type_rust(t)?;
                quote! { std::ptr::NonNull::<#typ> }
            }
        })
    }
}

#[derive(Default)]
struct ArgumentTokens {
    declaration: TokenStream,
    returns: TokenStream,
}

fn callback_fn_ident() -> Ident {
    ident("JsCallbackFn")
}

fn tuple_type(items: &[TokenStream]) -> TokenStream {
    match items.len() {
        0 => quote! { () },
        1 => {
            let first = &items[0];
            quote! { (#first,) }
        }
        _ => quote! { (#(#items),*) },
    }
}

fn tuple_expr(items: &[TokenStream]) -> TokenStream {
    match items.len() {
        0 => quote! { () },
        1 => {
            let first = &items[0];
            quote! { (#first,) }
        }
        _ => quote! { (#(#items),*) },
    }
}
